apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      serviceAccountName: default
      containers:
        - name: todo-app
          image: "491085397166.dkr.ecr.us-east-1.amazonaws.com/wiz-tech-exercise-app:e424410a5e1cd01dc5c2533d0fdd3285c421ac2e"
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://10.0.1.42:27017/todo-db"
