name: Deploy Insecure AWS Infrastructure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://CF-template-insecure-wiz-env

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file CF-template-insecure-wiz-env \
            --stack-name WizInsecureStack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides KeyName=wiz-ssh-key1